language: java
jdk:
  - oraclejdk8

env:
  global:
    - SQLSERVERHOSTNAME=sql-server
    - SQLCMD=/opt/mssql-tools/bin/sqlcmd
    - WORKING_DIR=/tifsa-build/
    - DB_NAME=tifsadb
    - DB_PASSWORD=Password1!
    - EXECSQL="docker exec client $SQLCMD -S $SQLSERVERHOSTNAME -U sa -P $DB_PASSWORD"

services:
  - docker

before_install:
  - docker pull microsoft/mssql-server-linux

install:
  - docker network create docker_net
  - docker build -t sql-server-client -f Dockerfile-travis .
  - docker run --name=$SQLSERVERHOSTNAME --net=docker_net -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password1!' -p 1433:1433 --name=$SQLSERVERHOSTNAME -d microsoft/mssql-server-linux
  - docker run --name=client --net=docker_net -t -d -w $WORKING_DIR sql-server-client
  - docker ps -a

before_script:
  # create database
  - $EXECSQL -d master -Q "CREATE DATABASE $DB_NAME"
  # download sql scripts for tifsa db
  - docker exec client git clone https://$GIT_USER_TOKEN@github.com/chrisf/tifsa-sql.git

script:
  # run create scripts
  - $EXECSQL -d $DB_NAME -i "tifsa-sql/Scripts/Create Scripts/Master Create.sql"
  # run alter scripts
  - $EXECSQL -d $DB_NAME -i "tifsa-sql/Scripts/Alter Scripts/Master Alter.sql"
  # run insert scripts
  - mvn -DdataSource=testDataSource clean test

addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  email: false
