language: java
jdk:
  - oraclejdk8

sudo: false

script:
  # -q=hide [info] line, -X=show debug messages
  - mvn -q clean test

addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  email: false
