language: java
jdk:
  - oraclejdk8

env:
  global:
    - SQLSERVERHOSTNAME=sql

services:
  - docker

before_install:
  - docker pull microsoft/mssql-server-linux
  - docker pull ubuntu:xenial

install:
  - docker network create docker_net
  - docker build -t sql-server-client -f Dockerfile-travis .
  - docker run --name=$SQLSERVERHOSTNAME --net=docker_net -e 'ACCEPT_EULA=Y' -e 'SA_PASSWORD=Password1!' -p 1433:1433 --name=localhost -d microsoft/mssql-server-linux
  - docker run --name=client --net=docker_net -t -d sql-server-client
  - docker ps -a
  
before_script:
  - docker exec client sqlcmd -S $SQLSERVERHOSTNAME -U sa -P 'Password1!' -Q "CREATE DATABASE tifsadb"
  - git clone git@github.com:chrisf/tifsa-sql.git

script:
  - mvn -DdataSource=testDataSource clean test

after_script:
  - docker stop client
  - docker ps -a

addons:
  apt:
    packages:
      - oracle-java8-installer

notifications:
  email: false
