-- Insert countries
INSERT INTO tifsa.AddCountry(AddCountryName) VALUES
("Afghanistan"),
("Albania"),
("Algeria"),
("Andorra"),
("Angola"),
("Antigua and Barbuda"),
("Argentina"),
("Armenia"),
("Australia"),
("Austria"),
("Azerbaijan"),
("Bahamas"),
("Bahrain"),
("Bangladesh"),
("Barbados"),
("Belarus"),
("Belgium"),
("Belize"),
("Benin"),
("Bhutan"),
("Bolivia"),
("Bosnia and Herzegovina"),
("Botswana"),
("Brazil"),
("Brunei Darussalam"),
("Bulgaria"),
("Burkina Faso"),
("Burundi"),
("Cabo Verde"),
("Cambodia"),
("Cameroon"),
("Canada"),
("Central African Republic"),
("Chad"),
("Chile"),
("China"),
("Colombia"),
("Comoros"),
("Congo"),
("Costa Rica"),
("Côte d’Ivoire"),
("Croatia"),
("Cuba"),
("Cyprus"),
("Czech Republic"),
("Democratic People's Republic of Korea (North Korea)"),
("Democratic Republic of the Cong"),
("Denmark"),
("Djibouti"),
("Dominica"),
("Dominican Republic"),
("Ecuador"),
("Egypt"),
("El Salvador"),
("Equatorial Guinea"),
("Eritrea"),
("Estonia"),
("Ethiopia"),
("Fiji"),
("Finland"),
("France"),
("Gabon"),
("Gambia"),
("Georgia"),
("Germany"),
("Ghana"),
("Greece"),
("Grenada"),
("Guatemala"),
("Guinea"),
("Guinea-Bissau"),
("Guyana"),
("Haiti"),
("Honduras"),
("Hungary"),
("Iceland"),
("India"),
("Indonesia"),
("Iran"),
("Iraq"),
("Ireland"),
("Israel"),
("Italy"),
("Jamaica"),
("Japan"),
("Jordan"),
("Kazakhstan"),
("Kenya"),
("Kiribati"),
("Kuwait"),
("Kyrgyzstan"),
("Lao People's Democratic Republic (Laos)"),
("Latvia"),
("Lebanon"),
("Lesotho"),
("Liberia"),
("Libya"),
("Liechtenstein"),
("Lithuania"),
("Luxembourg"),
("Macedonia"),
("Madagascar"),
("Malawi"),
("Malaysia"),
("Maldives"),
("Mali"),
("Malta"),
("Marshall Islands"),
("Mauritania"),
("Mauritius"),
("Mexico"),
("Micronesia (Federated States of)"),
("Monaco"),
("Mongolia"),
("Montenegro"),
("Morocco"),
("Mozambique"),
("Myanmar"),
("Namibia"),
("Nauru"),
("Nepal"),
("Netherlands"),
("New Zealand"),
("Nicaragua"),
("Niger"),
("Nigeria"),
("Norway"),
("Oman"),
("Pakistan"),
("Palau"),
("Panama"),
("Papua New Guinea"),
("Paraguay"),
("Peru"),
("Philippines"),
("Poland"),
("Portugal"),
("Qatar"),
("Republic of Korea (South Korea)"),
("Republic of Moldova"),
("Romania"),
("Russian Federation"),
("Rwanda"),
("Saint Kitts and Nevis"),
("Saint Lucia"),
("Saint Vincent and the Grenadines"),
("Samoa"),
("San Marino"),
("Sao Tome and Principe"),
("Saudi Arabia"),
("Senegal"),
("Serbia"),
("Seychelles"),
("Sierra Leone"),
("Singapore"),
("Slovakia"),
("Slovenia"),
("Solomon Islands"),
("Somalia"),
("South Africa"),
("South Sudan"),
("Spain"),
("Sri Lanka"),
("Sudan"),
("Suriname"),
("Swaziland"),
("Sweden"),
("Switzerland"),
("Syrian Arab Republic"),
("Tajikistan"),
("Thailand"),
("Timor-Leste"),
("Togo"),
("Tonga"),
("Trinidad and Tobago"),
("Tunisia"),
("Turkey"),
("Turkmenistan"),
("Tuvalu"),
("Uganda"),
("Ukraine"),
("United Arab Emirates"),
("United Kingdom of Great Britain and Northern Ireland"),
("United Republic of Tanzania"),
("United States of America"),
("Uruguay"),
("Uzbekistan"),
("Vanuatu"),
("Venezuela"),
("Vietnam"),
("Yemen"),
("Zambia"),
("Zimbabwe");

-- Insert states
-- US states
INSERT INTO tifsa.AddState(AddCountryID, AddStateName, AddStateAbbreviation) VALUES
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Alabama", "AL"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Alaska", "AK"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Arizona", "AZ"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Arkansas", "AR"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "California", "CA"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Colorado", "CO"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Connecticut", "CT"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Delaware", "DE"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Florida", "FL"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Georgia", "GA"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Hawaii", "HI"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Idaho", "ID"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Illinois", "IL"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Indiana", "IN"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Iowa", "IA"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Kansas", "KS"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Kentucky", "KY"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Louisiana", "LA"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Maine", "ME"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Maryland", "MD"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Massachusetts", "MA"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Michigan", "MI"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Minnesota", "MN"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Mississippi", "MS"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Missouri", "MO"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Montana", "MT"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Nebraska", "NE"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Nevada", "NV"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "New Hampshire", "NH"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "New Jersey", "NJ"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "New Mexico", "NM"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "New York", "NY"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "North Carolina", "NC"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "North Dakota", "ND"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Ohio", "OH"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Oklahoma", "OK"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Oregon", "OR"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Pennsylvania", "PA"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Rhode Island", "RI"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "South Carolina", "SC"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "South Dakota", "SD"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Tennessee", "TN"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Texas", "TX"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Utah", "UT"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Vermont", "VT"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Virginia", "VA"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Washington", "WA"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "West Virginia", "WV"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Wisconsin", "WI"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "United States of America"), "Wyoming", "WY");

-- Mexican states and districts
INSERT INTO tifsa.AddState(AddCountryID, AddStateName, AddStateAbbreviation) VALUES
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Aguascalientes", "AG"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Baja California", "BJ"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Baja California Sur", "BS"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Campeche", "CP"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Chiapas", "CH"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Chihuahua", "CI"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Coahuila", "CU"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Colima", "CL"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Durango", "DF"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Guanajuato", "DG"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Guerrero", "GJ"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Hidalgo", "GR"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Jalisco", "HG"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Mexico", "JA"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Mexico City (Federal District)", "EM"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Michoacan", "MH"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Morelos", "MR"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Nayarit", "NA"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Nuevo Leon", "NL"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Oaxaca", "OA"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Puebla", "PU"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Queretaro", "QA"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Quintana Roo", "QR"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "San Luis Potosi", "SL"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Sinaloa", "SI"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Sonora", "SO"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Tabasco", "TA"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Tamaulipas", "TM"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Tlaxcala", "TL"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Veracruz", "VZ"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Yucatan", "YC"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Mexico"), "Zacatecas", "ZT");

-- Canadian provinces
INSERT INTO tifsa.AddState(AddCountryID, AddStateName, AddStateAbbreviation) VALUES
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Canada"), "Alberta", "AB"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Canada"), "British Columbia", "BC"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Canada"), "Manitoba", "MB"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Canada"), "New Brunswick", "NB"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Canada"), "Newfoundland and Labrador", "NL"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Canada"), "Nova Scotia", "NS"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Canada"), "Ontario", "ON"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Canada"), "Prince Edward Island", "PE"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Canada"), "Quebec", "QC"),
((SELECT AddCountryID FROM AddCountry WHERE AddCountryName = "Canada"), "Saskatchewan", "SK");
